### ISSUE TITLE
Using <ul> content in Generico tabs

### ISSUE THREAD

**Issue by Kasuare** [justinhunt/moodle-generico_presets#2]
I've produced an unintentional effect inside the tabs. The filter with the tabitem works fine, but as soon as the content itself is filled with an unsorted list things get strange. 

The script identifies the list inside the tabitem as a .child() and appends the item id and title to it. 

There should be a workaround ignoring the content of the children in tabs.

**Comment by Kasuare** [comment]
just seen, that bullet points wont work at the description. Sad to hear that.

**Comment by justinhunt** [comment]
Thanks Kasuare. Yes I feel the pain. It has affected me too. I think it can be solved actually. But it has always been simpler to just use asterisks (*) instead. Appreciate you writing in on it.

**Comment by Kasuare** [comment]
I've read about the markdown option using asterisks (to create bullet points), but it seems that it wont run using the atto editor?

**Comment by justinhunt** [comment]
I do not think Markdown can be used to get around this. If you really want to use bullets in your tabs, its probably best to use bootstrap tabs. These ones are jquery ui tabs. I can not give too much advice on it here. But when I get a chance I will make a template up.
